services:
  xpipe-webtop:
    build:
      context: ./../
      dockerfile: Dockerfile
    hostname: xpipe-webtop
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 3000:3000
      - 3001:3001
      - 21222:21222
      - 21721:21721
      - 21722:21722
    shm_size: 256mb
    restart: unless-stopped
