#!/bin/sh

### BEGIN INIT INFO
# Provides:	  polkitd
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the polkitd daemon
# Description:       starts the polkitd daemon
### END INIT INFO

PID=/run/polkitd.pid
DAEMON=/usr/lib/polkit-1/polkitd
NAME=polkitd

set -e

. /lib/lsb/init-functions

case "$1" in
	start|reload|restart|force-reload)
		start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON > /dev/null
	;;
	stop|status)
	  start-stop-daemon --stop --quiet --pidfile $PID --name $NAME
	;;
esac